### ISSUE TITLE
请问，对话任务中的数据是什么形式的呢？

### ISSUE THREAD

**Issue by zhihao-chen** [Liadrinz/transformers-unilm#1]
多轮对话的话，您是采用什么模版将所有对话合并为一段文本的呢。谢谢

**Comment by Liadrinz** [comment]
我没有试过用unilm做多轮对话诶，您可以参考其他工作中多轮对话的做法。

**Comment by zhihao-chen** [comment]
好的谢谢，那你这个example/dialogue里的数据是什么数据呀

**Comment by Liadrinz** [comment]
example/dialogue是用来做单轮对话训练的，在 STC数据集([论文](https://arxiv.org/abs/1503.02364)|[下载](https://pan.baidu.com/s/1GKwGDV-0e6dcRR-hVrrKGw?pwd=rev5)) 上尝试了一下，效果不好就没有进一步的工作了，因为使用的开源预训练unilm模型没有在大规模对话语料上预训练过，所以很难生成对话。大规模中文对话语料库可以看看这个工作[thu-coai/CDial-GPT](https://github.com/thu-coai/CDial-GPT)

**Comment by zhihao-chen** [comment]
好的，谢谢，CDialGPT这个已经试过了，效果也不太好
